name: CurriculumVitae
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  form_validator: ">=0.1.1 <2.0.0"
  email_validator: "^2.0.1"


  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/pascual.jpg
    - images/educ.jpg
    - images/bg.png
    - images/logo.png
    - images/philcst.jpg
    - images/home.gif
    - assets/images/secured.gif
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
    - family: Satisfy
      fonts:
        - asset: fonts/Satisfy-Regular.ttf
    - family: Orbitron
      fonts:
        - asset: fonts/Orbitron-VariableFont_wght.ttf
    - family: BungeeSpice
      fonts:
        - asset: fonts/BungeeSpice-Regular.ttf
    - family: Acme
      fonts:
        - asset: fonts/Acme-Regular.ttf





